
# 连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root

# 配置mapper.xml路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.root.dao
